@startuml

skinparam monochrome true
hide empty members

class Main
Main --> Logic.Logic
Main --> User.User

namespace Logic {

interface Logic
class LogicImpl
Logic <|.. LogicImpl

class ResumeGenerator
class AchievementSelector
LogicImpl *-- "1" ResumeGenerator
LogicImpl --> AchievementSelector
LogicImpl --> User.AchievementList

class AchievementSelection
AchievementSelector *-- "1" AchievementSelection

ResumeGenerator --> AchievementSelection
ResumeGenerator --> User.ResumeImpl
ResumeGenerator --> User.AchievementList
}

namespace User {

interface User
class UserImpl {
    PersonName name
}
User <|.. UserImpl
UserImpl *-- "1" AchievementList
UserImpl *-- "1" ResumeList

interface Achievement
class PersonalProject {
    AchievementName name
    AchievementDescription description
}
interface AchievementList
class AchievementListImpl
Achievement <|.. PersonalProject
AchievementList <|.. AchievementListImpl
AchievementListImpl o-- "*" Achievement

interface Resume
class ResumeImpl {
    ResumeName name
    ResumeContents contents
}
interface ResumeList
class ResumeListImpl
Resume <|.. ResumeImpl
ResumeList <|.. ResumeListImpl
ResumeListImpl o-- "*" Resume

}

@enduml