@startuml

skinparam monochrome true
hide empty members

class Main
interface Frontend

Main *-- "1" Backend.Backend
Main *-- "1" Frontend
Frontend --> Backend.Backend

namespace Backend {

interface Backend
class BackendImpl
Backend <|.. BackendImpl

interface Storage
interface Account
interface ResumeGenerator
interface ResumeSaver
interface LoginManager

BackendImpl *-- "1" Storage
BackendImpl *-- "1" Account
BackendImpl *-- "1" ResumeGenerator
BackendImpl *-- "1" ResumeSaver
BackendImpl *-- "1" LoginManager

}

@enduml