@startuml

skinparam monochrome true
hide empty members

class Main
Main --> Logic.ResumeGenerator
Main o-- "1" Model.User

namespace Logic {

interface ResumeGenerator
class ResumeGeneratorImpl
class AchievementSelector

ResumeGenerator <|.. ResumeGeneratorImpl
ResumeGeneratorImpl *-- "1" AchievementSelector
ResumeGeneratorImpl --> Model.ResumeImpl
ResumeGeneratorImpl --> Model.AchievementList
}

namespace Model {

interface User
class UserImpl {
    PersonName name
}
User <|.. UserImpl
UserImpl *-- "1" AchievementList
UserImpl *-- "1" ResumeList

interface Achievement
class PersonalProject {
    AchievementName name
    AchievementDescription description
}
interface AchievementList
class AchievementListImpl
Achievement <|.. PersonalProject
AchievementList <|.. AchievementListImpl
AchievementListImpl o-- "*" Achievement

interface Resume
class ResumeImpl {
    ResumeName name
    ResumeContents contents
}
interface ResumeList
class ResumeListImpl
Resume <|.. ResumeImpl
ResumeList <|.. ResumeListImpl
ResumeListImpl o-- "*" Resume

}

@enduml